export const OUTSIDE_LEFT_WIDTH = 100
export const STORAGE_UNIT_WIDTH = 120
export const OUTSIDE_RIGHT_WIDTH = 100
export const ROOM_WIDTH = OUTSIDE_LEFT_WIDTH + STORAGE_UNIT_WIDTH + OUTSIDE_RIGHT_WIDTH
export const ROOM_HEIGHT = 180

export const STORAGE_UNIT_START_X = OUTSIDE_LEFT_WIDTH
export const STORAGE_UNIT_END_X = OUTSIDE_LEFT_WIDTH + STORAGE_UNIT_WIDTH
