import type { ServerNode, Part } from './types'

export const AMBIENT_TEMP = 25 // °C
export const GRID_CELL_SIZE = 10 // cm per cell
export const ROOM_WIDTH_MAX = 550 // Big enough for debug and transfer zone
export const ROOM_HEIGHT_MAX = 250

export const GRID_COLS = Math.ceil(ROOM_WIDTH_MAX / GRID_CELL_SIZE)
export const GRID_ROWS = Math.ceil(ROOM_HEIGHT_MAX / GRID_CELL_SIZE)

export function createInitialGrid(): number[][] {
  const grid: number[][] = []
  for (let y = 0; y < GRID_ROWS; y++) {
    const row = []
    for (let x = 0; x < GRID_COLS; x++) {
      row.push(AMBIENT_TEMP)
    }
    grid.push(row)
  }
  return grid
}

// Heat capacity constant (Joules per °C per cm^2)
const THERMAL_MASS_PER_AREA = 2 // Adjusted for better gameplay response

export function calculateServerThermalMass(server: ServerNode): number {
  const casePart = server.installedParts.find(p => p.kind === 'CASE')
  const area = casePart ? casePart.width * casePart.height : 100
  return area * THERMAL_MASS_PER_AREA
}

export function getServerOperatingLimits(server: ServerNode) {
  let maxOperatingTemp = Infinity
  let criticalTemp = Infinity

  for (const part of server.installedParts) {
    if (part.maxOperatingTemp !== undefined && part.maxOperatingTemp < maxOperatingTemp) {
      maxOperatingTemp = part.maxOperatingTemp
    }
    if (part.criticalTemp !== undefined && part.criticalTemp < criticalTemp) {
      criticalTemp = part.criticalTemp
    }
  }

  // Fallbacks if parts don't specify limits
  if (maxOperatingTemp === Infinity) maxOperatingTemp = 85
  if (criticalTemp === Infinity) criticalTemp = 105

  return { maxOperatingTemp, criticalTemp }
}

export function tickThermal(
  serverTemps: Record<string, number>,
  roomGrid: number[][],
  servers: ServerNode[],
  serverWatts: Record<string, number>, // Watts generated by each server this tick
  dtSeconds: number
) {
  const k_air = 0.5 // Conductivity between air cells
  const k_case_air = 1.0 // Conductivity between server case and surrounding air
  const cooling_factor = 0.05 // Base cooling to ambient per tick in empty cells

  // 1. Server generates heat and exchanges with overlapping room cells
  for (const server of servers) {
    if (serverTemps[server.id] === undefined) {
      serverTemps[server.id] = AMBIENT_TEMP
    }

    const watts = serverWatts[server.id] || 0
    const thermalMass = calculateServerThermalMass(server)

    // Heat generated by power: ΔT = (Watts * dt) / thermalMass
    const heatDelta = (watts * dtSeconds) / thermalMass
    serverTemps[server.id] += heatDelta

    // Find case and overlapping cells
    const casePart = server.installedParts.find(p => p.kind === 'CASE')
    if (casePart && server.x !== undefined && server.y !== undefined) {
      const startCol = Math.floor(server.x / GRID_CELL_SIZE)
      const endCol = Math.floor((server.x + casePart.width) / GRID_CELL_SIZE)
      const startRow = Math.floor(server.y / GRID_CELL_SIZE)
      const endRow = Math.floor((server.y + casePart.height) / GRID_CELL_SIZE)

      // Surrounding cells for passive exhaust/intake
      const surroundingCells: {r: number, c: number}[] = []
      for (let r = startRow - 1; r <= endRow + 1; r++) {
        for (let c = startCol - 1; c <= endCol + 1; c++) {
          // Exclude interior overlapping cells for surrounding
          if (r >= startRow && r <= endRow && c >= startCol && c <= endCol) continue;
          if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) {
            surroundingCells.push({r, c})
          }
        }
      }

      // 1A: Passive Heat Transfer (Case surface to overlapping cells)
      let overlappingCells = 0
      for (let r = startRow; r <= endRow; r++) {
        for (let c = startCol; c <= endCol; c++) {
          if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) {
            overlappingCells++
          }
        }
      }

      const CELL_THERMAL_MASS = 100.0 // abstract thermal mass per air cell

      if (overlappingCells > 0) {
        for (let r = startRow; r <= endRow; r++) {
          for (let c = startCol; c <= endCol; c++) {
            if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) {
              const cellTemp = roomGrid[r][c]
              const serverTemp = serverTemps[server.id]
              const tempDiff = serverTemp - cellTemp
              
              // Case passive conductivity: ~5 W/°C total
              let heatJoules = (tempDiff * 5.0 * dtSeconds) / overlappingCells
              
              const maxHeat = Math.abs(tempDiff) * Math.min(thermalMass, CELL_THERMAL_MASS) * 0.5
              if (Math.abs(heatJoules) > maxHeat) {
                heatJoules = maxHeat * Math.sign(heatJoules)
              }
              
              serverTemps[server.id] -= heatJoules / thermalMass
              roomGrid[r][c] += heatJoules / CELL_THERMAL_MASS 
            }
          }
        }
      }

      // 1B: Forced Convection (Fans)
      const fans = server.installedParts.filter(p => p.kind === 'FAN') as import('./types').FanPart[]
      if (fans.length > 0) {
        let intakeFlow = 0
        let intakeTempSum = 0
        let exhaustFlow = 0
        const exhaustTargets: { fan: import('./types').FanPart, cells: {r: number, c: number}[] }[] = []

        for (const fan of fans) {
          const slot = casePart.slots?.find(s => s.installedPartId === fan.id)
          const position = slot?.position || 'REAR'
          
          let targetCells: {r: number, c: number}[] = []
          
          if (position === 'TOP') {
            const r = startRow - 1
            for (let c = startCol; c <= endCol; c++) {
              if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) targetCells.push({r, c})
            }
          } else if (position === 'LEFT') {
            const c = startCol - 1
            for (let r = startRow; r <= endRow; r++) {
              if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) targetCells.push({r, c})
            }
          } else if (position === 'RIGHT') {
            const c = endCol + 1
            for (let r = startRow; r <= endRow; r++) {
              if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) targetCells.push({r, c})
            }
          } else {
            // REAR or unknown defaults to all surrounding
            targetCells = surroundingCells
          }

          if (targetCells.length === 0) targetCells = surroundingCells

          if (fan.direction === 'INTAKE') {
            intakeFlow += fan.flowRate
            const avgTarget = targetCells.reduce((sum, cell) => sum + roomGrid[cell.r][cell.c], 0) / targetCells.length
            intakeTempSum += avgTarget * fan.flowRate
          } else {
            exhaustFlow += fan.flowRate
            exhaustTargets.push({ fan, cells: targetCells })
          }
        }

        let tIntakeAir = AMBIENT_TEMP
        if (intakeFlow > 0) {
          tIntakeAir = intakeTempSum / intakeFlow
        } else if (surroundingCells.length > 0) {
          tIntakeAir = surroundingCells.reduce((sum, cell) => sum + roomGrid[cell.r][cell.c], 0) / surroundingCells.length
        }

        const totalFlow = intakeFlow + exhaustFlow
        // Flow rate (CFM) -> m^3/s -> mass flow * Cp -> k_fan (W/°C)
        // Roughly: 1 CFM = 0.57 W/°C for air
        const k_total = totalFlow * 0.57

        const serverTemp = serverTemps[server.id]
        const Q = k_total * (serverTemp - tIntakeAir) // Watts removed
        
        let heatJoules = Q * dtSeconds
        
        // Calculate the total thermal mass of the exhaust target cells to clamp properly
        let targetCellsCount = exhaustFlow > 0 
          ? exhaustTargets.reduce((sum, t) => sum + t.cells.length, 0)
          : surroundingCells.length
          
        if (targetCellsCount === 0) targetCellsCount = 1
        const targetThermalMass = targetCellsCount * 100.0 // using CELL_THERMAL_MASS
        
        // Clamp to prevent instability
        const maxForcedHeat = Math.abs(serverTemp - tIntakeAir) * Math.min(thermalMass, targetThermalMass) * 0.5
        if (Math.abs(heatJoules) > maxForcedHeat) {
          heatJoules = maxForcedHeat * Math.sign(heatJoules)
        }

        serverTemps[server.id] -= heatJoules / thermalMass

        // Dump heat into exhaust targets
        if (exhaustFlow > 0) {
          for (const target of exhaustTargets) {
            const share = heatJoules * (target.fan.flowRate / exhaustFlow)
            if (target.cells.length > 0) {
              const perCell = share / target.cells.length
              for (const cell of target.cells) {
                roomGrid[cell.r][cell.c] += perCell / 100.0 // using CELL_THERMAL_MASS
              }
            }
          }
        } else {
          // Dump passively into surrounding cells
          if (surroundingCells.length > 0) {
            const perCell = heatJoules / surroundingCells.length
            for (const cell of surroundingCells) {
              roomGrid[cell.r][cell.c] += perCell / 100.0
            }
          }
        }
      }
    }
  }

  // 2. Cellular Automata for room air (diffusion)
  const nextGrid = createInitialGrid()
  for (let r = 0; r < GRID_ROWS; r++) {
    for (let c = 0; c < GRID_COLS; c++) {
      let temp = roomGrid[r][c]
      
      let neighborSum = 0
      let validNeighbors = 0
      
      if (r > 0) { neighborSum += roomGrid[r-1][c]; validNeighbors++ }
      if (r < GRID_ROWS - 1) { neighborSum += roomGrid[r+1][c]; validNeighbors++ }
      if (c > 0) { neighborSum += roomGrid[r][c-1]; validNeighbors++ }
      if (c < GRID_COLS - 1) { neighborSum += roomGrid[r][c+1]; validNeighbors++ }

      const avgNeighbor = neighborSum / validNeighbors
      
      let diffusionAmount = (avgNeighbor - temp) * k_air * dtSeconds
      // Clamp diffusion for stability
      const maxDiffusion = Math.abs(avgNeighbor - temp) * 0.5
      if (Math.abs(diffusionAmount) > maxDiffusion) {
        diffusionAmount = maxDiffusion * Math.sign(diffusionAmount)
      }
      
      temp += diffusionAmount
      
      // Ambient cooling (air conditioning)
      temp += (AMBIENT_TEMP - temp) * cooling_factor * dtSeconds

      nextGrid[r][c] = temp
    }
  }

  // Copy back
  for (let r = 0; r < GRID_ROWS; r++) {
    for (let c = 0; c < GRID_COLS; c++) {
      roomGrid[r][c] = nextGrid[r][c]
    }
  }
}
